#:schema node_modules/wrangler/config-schema.json
name = "smail"
compatibility_date = "2024-09-25"
main = "app/worker.ts"
assets = { directory = "./build/client" }

[observability]
enabled = true

[[kv_namespaces]]
binding = "KV"
id = "d5e06b2057334473b9734819c8c9fff2"

[[d1_databases]]
binding = "DB"
database_name = "smail"
database_id = "031890ed-8084-443e-9c20-aa25067a0542"
preview_database_id = "031890ed-8084-443e-9c20-aa25067a0542"
migrations_dir = "app/drizzle"
